import type { Metadata } from "next";
import dynamic from "next/dynamic";
const HomeLayout = dynamic(() => import("@/layout/HomeLayout"), { ssr: false })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <HomeLayout>
      {children}
    </HomeLayout>
  );
}
